# Generated by Django 5.2.8 on 2025-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pravence_id', models.CharField(max_length=255)),
                ('system_type', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
