# Generated by Django 5.2.8 on 2025-12-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_user_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=255)),
                ('record_id', models.IntegerField(max_length=255)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mineral_amount', models.IntegerField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('count_90days', models.IntegerField(max_length=20)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('leader_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('company_type', models.CharField(max_length=100)),
                ('TIN_number', models.CharField(max_length=50, unique=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Maktoob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maktoob_type', models.CharField(max_length=255)),
                ('maktoob_number', models.IntegerField(max_length=255)),
                ('sadir_date', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_maktoobs', to='test1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mineral_description', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Momp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=255)),
                ('momp', models.CharField(max_length=255)),
                ('momp_province', models.CharField(max_length=255)),
                ('scale_name', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('developed_by', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('mineral_amount', models.IntegerField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mineral_total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('royalty_receipt_number', models.IntegerField(max_length=255)),
                ('weighing_total_price', models.IntegerField(max_length=255)),
                ('haq_wazan_receipt_number', models.IntegerField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_purchases', to='test1.company')),
                ('maktoob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maktoob_purchases', to='test1.maktoob')),
                ('mineral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mineral_purchases', to='test1.mineral')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('weighing_price', models.IntegerField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('user_type', models.CharField(max_length=50)),
                ('archive', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('plate_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=200)),
                ('empty_weight', models.IntegerField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=255)),
                ('excel_count', models.IntegerField(max_length=20)),
                ('tire_count', models.IntegerField(max_length=255)),
                ('allow_weight_ton', models.IntegerField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_weight', models.IntegerField(max_length=255)),
                ('mineral_net_weight', models.IntegerField(max_length=255)),
                ('control_weight', models.IntegerField(max_length=255)),
                ('transfor_type', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('discharge_place', models.CharField(max_length=255)),
                ('bill_number', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='vechal_type',
        ),
        migrations.RenameField(
            model_name='scale',
            old_name='pravence_id',
            new_name='province_id',
        ),
        migrations.AlterField(
            model_name='scale',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='momp',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momp', to='test1.scale'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_purchases', to='test1.scale'),
        ),
        migrations.AddField(
            model_name='balance',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balances', to='test1.purchase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_purchases', to='test1.unit'),
        ),
        migrations.AddField(
            model_name='mineral',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minerals', to='test1.unit'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_purchases', to='test1.user'),
        ),
        migrations.AddField(
            model_name='maktoob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_maktoobs', to='test1.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='test1.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicle',
            field=models.ManyToManyField(blank=True, related_name='companies', to='test1.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='test1.vehicletype'),
        ),
        migrations.AddField(
            model_name='weight',
            name='mineral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mineral_weights', to='test1.mineral'),
        ),
        migrations.AddField(
            model_name='weight',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_weights', to='test1.purchase'),
        ),
        migrations.AddField(
            model_name='weight',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_weights', to='test1.scale'),
        ),
        migrations.AddField(
            model_name='weight',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_weights', to='test1.unit'),
        ),
        migrations.AddField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_weights', to='test1.user'),
        ),
        migrations.AddField(
            model_name='weight',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_weights', to='test1.vehicle'),
        ),
    ]
