# Generated by Django 5.2.9 on 2026-01-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'permissions': [('cancel_vehicle', 'Can cancel vehicle')]},
        ),
    ]
