# Generated by Django 5.2.9 on 2026-01-05 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auditlog_balance_company_maktoob_mineral_momp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maktoob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_maktoobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_weights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='balance',
            name='count_90days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='balance',
            name='mineral_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maktoob',
            name='maktoob_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='haq_wazan_receipt_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='mineral_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='royalty_receipt_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='weighing_total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='empty_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='allow_weight_ton',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='excel_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='tire_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='control_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='mineral_net_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='second_weight',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
