# Generated by Django 5.2.9 on 2026-01-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
