# Generated by Django 5.2.9 on 2026-01-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_at',
            field=models.DateField(),
        ),
    ]
