# Generated by Django 5.2.9 on 2026-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_alter_company_create_at_alter_company_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
