# Generated by Django 5.2.9 on 2026-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_alter_company_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maktoob',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maktoob',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='momp',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='momp',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
