# Generated by Django 5.2.9 on 2026-01-28 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_alter_auditlog_created_at_alter_balance_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 52, 3, 989471, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 2, 868893, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 8, 284482, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maktoob',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 10, 720944, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mineral',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 13, 421625, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='momp',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 16, 343021, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 18, 671583, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scale',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 20, 747375, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 25, 947919, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 32, 160817, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 34, 76991, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weight',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 5, 53, 36, 566082, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
