# Generated by Django 5.2.9 on 2026-01-28 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_alter_auditlog_created_at_alter_balance_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='update_at',
            field=models.DateField(auto_now=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='update_at',
            field=models.DateField(auto_now=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maktoob',
            name='update_at',
            field=models.DateField(auto_now=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='momp',
            name='update_at',
            field=models.DateField(auto_now=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='update_at',
            field=models.DateField(auto_now=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scale',
            name='update_at',
            field=models.DateField(auto_now=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='update_at',
            field=models.DateField(auto_now=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='update_at',
            field=models.DateField(auto_now=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weight',
            name='update_at',
            field=models.DateField(auto_now=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
    ]
