# Generated by Django 5.2.9 on 2026-01-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0010_alter_balance_update_at_alter_company_update_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='maktoob',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='mineral',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='momp',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='maktoob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mineral',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='momp',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
