# Generated by Django 5.2.9 on 2026-01-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0011_remove_auditlog_is_deleted_remove_balance_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
