# Generated by Django 5.2.9 on 2026-01-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0012_userprofile_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted_at',
        ),
    ]
