# Generated by Django 5.2.9 on 2026-01-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_remove_userprofile_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
