# Generated by Django 5.2.9 on 2026-01-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0014_user_deleted_at_userprofile_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted_at',
        ),
    ]
