# Generated by Django 5.2.9 on 2026-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0015_remove_user_deleted_at_remove_userprofile_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CascadeDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_by_model', models.CharField(max_length=255)),
                ('deleted_by_id', models.IntegerField()),
                ('cascade_model', models.CharField(max_length=255)),
                ('cascade_id', models.IntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['deleted_by_model', 'deleted_by_id'], name='test1_casca_deleted_5adbb0_idx'), models.Index(fields=['cascade_model', 'cascade_id'], name='test1_casca_cascade_263ac5_idx')],
            },
        ),
    ]
