# Generated by Django 5.2.9 on 2026-01-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0016_cascadedeletionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_id', models.IntegerField()),
                ('related_model', models.CharField(max_length=255)),
                ('related_id', models.IntegerField()),
                ('relationship_type', models.CharField(max_length=50)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deleted Relationship',
                'verbose_name_plural': 'Deleted Relationships',
                'indexes': [models.Index(fields=['model_name', 'model_id'], name='test1_delet_model_n_583c3d_idx'), models.Index(fields=['related_model', 'related_id'], name='test1_delet_related_f8601f_idx')],
            },
        ),
    ]
