# Generated by Django 5.2.9 on 2026-02-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0017_deletedrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='licence_number',
            field=models.CharField(default=122, max_length=255),
            preserve_default=False,
        ),
    ]
