# Generated by Django 5.2.9 on 2026-02-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0018_company_licence_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='unit_price',
        ),
    ]
