# Generated by Django 5.2.9 on 2026-02-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0019_remove_purchase_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
            preserve_default=False,
        ),
    ]
