# Generated by Django 5.2.9 on 2026-02-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0020_purchase_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='mineral_amount',
            new_name='remaining_mineral_amount',
        ),
    ]
