# Generated by Django 5.2.9 on 2026-02-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0021_rename_mineral_amount_balance_remaining_mineral_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_balances', to='test1.company'),
        ),
        migrations.AddField(
            model_name='balance',
            name='mineral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mineral_balances', to='test1.mineral'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='balance_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weight',
            name='balance_updated',
            field=models.BooleanField(default=False),
        ),
    ]
