# Generated by Django 5.2.9 on 2026-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0022_balance_company_balance_mineral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='remaining_mineral_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('company', 'mineral')},
        ),
    ]
