# Generated by Django 5.2.9 on 2026-02-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0023_alter_balance_remaining_mineral_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name': 'Balance', 'verbose_name_plural': 'Balances'},
        ),
        migrations.RemoveField(
            model_name='balance',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='balance_updated',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='balance_updated',
        ),
        migrations.AlterField(
            model_name='balance',
            name='company',
            field=models.ForeignKey(default=112, on_delete=django.db.models.deletion.CASCADE, related_name='company_balances', to='test1.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='count_90days',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='balance',
            name='mineral',
            field=models.ForeignKey(default=1213, on_delete=django.db.models.deletion.CASCADE, related_name='mineral_balances', to='test1.mineral'),
            preserve_default=False,
        ),
    ]
