# Generated by Django 5.2.9 on 2026-02-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0024_alter_balance_options_remove_balance_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
    ]
