# Generated by Django 5.2.9 on 2026-02-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0025_remove_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='balance_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weight',
            name='balance_updated',
            field=models.BooleanField(default=False),
        ),
    ]
