# Generated by Django 5.2.9 on 2026-02-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0026_company_company_type_purchase_balance_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='transfor_type',
        ),
    ]
